services:
  postgres:
    image: postgres:17
    container_name: postgres
    hostname: postgres
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d postgres" ]
      interval: 3s
      timeout: 5s

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:8
    restart: always
    networks:
      - backend
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: postgres_data
    driver: local
  pgadmin_data:
    name: pgadmin_data
    driver: local

networks:
  backend:
    name: backend
    driver: bridge
